### ISSUE TITLE
Network Traffic Indicator Not Showing

### ISSUE THREAD

**Issue by isnrdra** [PixelExtended/manifest#2]
Hi, im building for Xiaomi Redmi Note 3 (kenzo), it booted up without any issue, but then when i turned on the Network Traffic Indicator in System>Device Customisation it doesn't work, tried changing auto hide threshold to 0 but it still doesn't show any net indicator in statusbar.

**Comment by ElytrA8** [comment]
Working fine For me I am maintainer of Redmi 5 (Rosy)

**Comment by ElytrA8** [comment]
![Screenshot_20201002-072945_Pixel_Launcher](https://user-images.githubusercontent.com/59019272/94880613-11271b80-0481-11eb-9f6b-da2ac979fad4.png)
