### ISSUE TITLE
why

### ISSUE THREAD

**Issue by java67** [PixelExtended/manifest#5]
error: vendor/overlay/navbar/GesturalNavigationRadiusVeryLow/Android.bp:17:1: mo
dule "GesturalNavigationRadiusVeryLow" already defined
       vendor/aosp/rro_overlays/GesturalNavigationRadiusVeryLow/Android.bp:17:1 
<-- previous definition here
error: vendor/aosp/rro_overlays/navbar/GesturalNavigationOverlayMedium/Android.b
p:17:1: module "GesturalNavigationOverlayMedium" already defined
       vendor/overlay/navbar/GesturalNavigationOverlayMedium/Android.bp:17:1 <--
 previous definition here
error: vendor/aosp/rro_overlays/navbar/GesturalNavigationOverlayLong/Android.bp:
17:1: module "GesturalNavigationOverlayLong" already defined
       vendor/overlay/navbar/GesturalNavigationOverlayLong/Android.bp:17:1 <-- p
revious definition here

**Comment by darkbeast69** [comment]
did u tried force syncing ??

**Comment by java67** [comment]
> did u tried force syncing ??

Same after resynchronizing twice

**Comment by darkbeast69** [comment]
@java67 This is not an real issues ...that overlay no longer exist @ vendor/aosp

**Comment by IMMANUEL44** [comment]
@java67 relax source is not released yet and its not a sync errror

**Comment by java67** [comment]
> @java67 relax source is not released yet and its not a sync errror

I got the good news from you, thank you

**Comment by darkbeast69** [comment]
@java67 Finsihed my build
