### ISSUE TITLE
Build Fails when moving file

### ISSUE THREAD

**Issue by dragonBall561** [PixelExtended/manifest#6]
I am building PixelExtended 11 for Motorola Doha (Moto G8 Plus)

```
[100% 26018/26018] build bacon
FAILED: bacon
/bin/bash -c "(mv  out/target/product/doha/PixelExtended_doha-11.0-20210610-1827-UNOFFICIAL.zip ) && (prebuilts/build-tools/path/linux-x86/md5sum out/target/product/doha/PixelExtended_doha-11.0-20210610-1827-UNOFFICIAL.zip | sed \"s|out/target/product/doha/||\" > out/target/product/doha/PixelExtended_doha-11.0-20210610-1827-UNOFFICIAL.zip.md5sum ) && (echo \"Package Complete: out/target/product/doha/PixelExtended_doha-11.0-20210610-1827-UNOFFICIAL.zip\" >&2 )"
mv: Need 2 arguments (see "mv --help")
ninja: build stopped: subcommand failed.
18:28:18 ninja failed with: exit status 1
```

**Comment by darkbeast69** [comment]
@dragonBall561 Bruh

**Comment by IMMANUEL44** [comment]
@dragonBall561 Check above there wil be some clues

**Comment by dragonBall561** [comment]
There aren't errors above that..

**Comment by IMMANUEL44** [comment]
@dragonBall561 All the best for the rest of ur build

**Comment by dragonBall561** [comment]
Ok ig. I just thought to ask here bc I didn't get responses anywhere else, for a LONG time.

**Comment by IMMANUEL44** [comment]
@dragonBall561 Try building again...check if u had used the corrext command mka bacon....lunched proper and if u have space .....cause no recent chnage on build/make nor vendor so no possible broken from rom side

**Comment by dragonBall561** [comment]
also, if you want to take a look at my full log:
[log.txt](https://github.com/PixelExtended/manifest/files/6640117/log.txt)

**Comment by IMMANUEL44** [comment]
@dragonBall561 [100% 26018/26018] build bacon
FAILED: bacon

close it .... do "source build/envsetup.sh && lunch aosp_<yourdevice>-userdebug && make installclean && mka bacon" and try

**Comment by dragonBall561** [comment]
same error.

**Comment by IMMANUEL44** [comment]
@dragonBall561 Sure abt that?? U sure u did "mka bacon" cause ur log says build bacon check once they must be something wrong or try force sync source once too

**Comment by dragonBall561** [comment]
yes i am 100000000000000% sure i did mka bacon. I will do a screen record for you if you want :)

**Comment by IMMANUEL44** [comment]
@dragonBall561 Nah nvm just asked to be sure cause the log said it ...try force sync and build

**Comment by dragonBall561** [comment]
so `repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags`, and then `source build/envsetup.sh && lunch aosp_doha-userdebug && make installclean && mka bacon`

**Comment by IMMANUEL44** [comment]
@dragonBall561 Yes

**Comment by dragonBall561** [comment]
ok some output from repo

```
frameworks/base/: discarding 1 commits
manifest/: discarding 1 commits
```

is this bad.

**Comment by IMMANUEL44** [comment]
@dragonBall561 Nope continue

**Comment by dragonBall561** [comment]
ok

**Comment by dragonBall561** [comment]
same error

**Comment by dragonBall561** [comment]
```
[100% 337/337] build bacon
FAILED: bacon
/bin/bash -c "(mv  out/target/product/doha/PixelExtended_doha-11.0-20210611-1810-UNOFFICIAL.zip ) && (prebuilts/build-tools/path/linux-x86/md5sum out/target/product/doha/PixelExtended_doha-11.0-20210611-1810-UNOFFICIAL.zip | sed \"s|out/target/product/doha/||\" > out/target/product/doha/PixelExtended_doha-11.0-20210611-1810-UNOFFICIAL.zip.md5sum ) && (echo \"Package Complete: out/target/product/doha/PixelExtended_doha-11.0-20210611-1810-UNOFFICIAL.zip\" >&2 )"
mv: Need 2 arguments (see "mv --help")
18:12:15 ninja failed with: exit status 1

#### failed to build some targets (04:55 (mm:ss)) ####
```

**Comment by IMMANUEL44** [comment]
@dragonBall561 Check if u have the zip in that location...if yes then ignore for now

**Comment by dragonBall561** [comment]
out/target/product/doha/ ?

**Comment by IMMANUEL44** [comment]
@IMMANUEL44 Okie flash it for now ....not sure about it....all the best for official incase u get btw

**Comment by dragonBall561** [comment]
??? theres nothing there...

**Comment by IMMANUEL44** [comment]
@dragonBall561 But u said there was

**Comment by dragonBall561** [comment]
out/target/product/doha/ ?
nothing there

**Comment by dragonBall561** [comment]
lol no

**Comment by IMMANUEL44** [comment]
@dragonBall561 Just grep the name fr source and check

**Comment by dragonBall561** [comment]
which name? doha? 

i have already tried `find . -type f -name *.zip | grep doha` no outputs

**Comment by IMMANUEL44** [comment]
@dragonBall561 If u have a file manager search doha ...eazy....or just find all zip in source instead of specifying

**Comment by dragonBall561** [comment]
oh, I forgot to mention, to build this, I am ssh-ing into a remote machine. so no gui.
my laptop is an absolute potato

**Comment by dragonBall561** [comment]
@IMMANUEL44 ?

**Comment by IMMANUEL44** [comment]
@dragonBall561 Sorry i slep since it was late ...just do this find . -type f -name Pixel*.zip

**Comment by dragonBall561** [comment]
its ok. I run command, there is no output.
